# Generated by Django 4.2.22 on 2025-08-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0004_actionuser_sectionuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionalFieldsTestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('conditional_field_active', models.CharField(blank=True, help_text='This field is only visible when status is ACTIVE', max_length=100)),
                ('conditional_field_inactive', models.CharField(blank=True, help_text='This field is only visible when status is INACTIVE', max_length=100)),
            ],
        ),
    ]
