name: Test

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: {}

jobs:
  tests:
    name: Python ${{ matrix.python-version }} / Django ${{ matrix.django-version }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.12"
          - "3.13"
          - "3.14"
        django-version:
          - "52"
          - "60"
          - "61"
          - "main"
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          enable-cache: true
          key: uv-${{ runner.os }}-py${{ matrix.python-version }}-dj${{ matrix.django-version }}-${{ hashFiles('uv.lock') }}
      - name: Run tox
        run: uv run -- tox run -e python$(echo ${{ matrix.python-version }} | tr -d .)-django${{ matrix.django-version }}
